// countries.js
// Lista de países con su código ISO, nombre y emoji de bandera (puedes reemplazar emojis por URLs de imágenes si prefieres)
export const countries = [
  { code: 'US', name: 'Estados Unidos', flagUrl: 'https://flagcdn.com/us.svg' },
  { code: 'BR', name: 'Brasil', flagUrl: 'https://flagcdn.com/br.svg' },
  { code: 'CN', name: 'China', flagUrl: 'https://flagcdn.com/cn.svg' },
  { code: 'IN', name: 'India', flagUrl: 'https://flagcdn.com/in.svg' },
  { code: 'JP', name: 'Japon', flagUrl: 'https://flagcdn.com/jp.svg' },
  { code: 'MX', name: 'Mexico', flagUrl: 'https://flagcdn.com/mx.svg' },
  { code: 'DE', name: 'Alemania', flagUrl: 'https://flagcdn.com/de.svg' },
  { code: 'FR', name: 'Francia', flagUrl: 'https://flagcdn.com/fr.svg' },
  { code: 'GB', name: 'Reino Unido', flagUrl: 'https://flagcdn.com/gb.svg' },
  { code: 'RU', name: 'Rusia', flagUrl: 'https://flagcdn.com/ru.svg' },
  { code: 'ZA', name: 'Sudáfrica', flagUrl: 'https://flagcdn.com/za.svg' },
  { code: 'AR', name: 'Argentina', flagUrl: 'https://flagcdn.com/ar.svg' },
  { code: 'CO', name: 'Colombia', flagUrl: 'https://flagcdn.com/co.svg' },
  { code: 'ES', name: 'España', flagUrl: 'https://flagcdn.com/es.svg' },
  { code: 'IT', name: 'Italia', flagUrl: 'https://flagcdn.com/it.svg' },
  { code: 'KR', name: 'Corea del Sur', flagUrl: 'https://flagcdn.com/kr.svg' },
  { code: 'CA', name: 'Canadá', flagUrl: 'https://flagcdn.com/ca.svg' },
  { code: 'AU', name: 'Australia', flagUrl: 'https://flagcdn.com/au.svg' },
  { code: 'NL', name: 'Países Bajos', flagUrl: 'https://flagcdn.com/nl.svg' },
  { code: 'SE', name: 'Suecia', flagUrl: 'https://flagcdn.com/se.svg' },
  { code: 'CH', name: 'Suiza', flagUrl: 'https://flagcdn.com/ch.svg' },
  { code: 'NO', name: 'Noruega', flagUrl: 'https://flagcdn.com/no.svg' },
  { code: 'DK', name: 'Dinamarca', flagUrl: 'https://flagcdn.com/dk.svg' },
  { code: 'FI', name: 'Finlandia', flagUrl: 'https://flagcdn.com/fi.svg' },
  { code: 'PL', name: 'Polonia', flagUrl: 'https://flagcdn.com/pl.svg' },
  { code: 'TR', name: 'Turquía', flagUrl: 'https://flagcdn.com/tr.svg' },
  { code: 'ID', name: 'Indonesia', flagUrl: 'https://flagcdn.com/id.svg' },
  { code: 'MY', name: 'Malasia', flagUrl: 'https://flagcdn.com/my.svg' },
  { code: 'PH', name: 'Filipinas', flagUrl: 'https://flagcdn.com/ph.svg' },
  { code: 'TH', name: 'Tailandia', flagUrl: 'https://flagcdn.com/th.svg' },
  { code: 'VN', name: 'Vietnam', flagUrl: 'https://flagcdn.com/vn.svg' },
  { code: 'EG', name: 'Egipto', flagUrl: 'https://flagcdn.com/eg.svg' },
  { code: 'KE', name: 'Kenia', flagUrl: 'https://flagcdn.com/ke.svg' },
  { code: 'NG', name: 'Nigeria', flagUrl: 'https://flagcdn.com/ng.svg' },
  { code: 'SA', name: 'Arabia Saudita', flagUrl: 'https://flagcdn.com/sa.svg' },
  { code: 'AE', name: 'Emiratos Árabes Unidos', flagUrl: 'https://flagcdn.com/ae.svg' },
  { code: 'BO', name: 'Bolivia', flagUrl: 'https://flagcdn.com/bo.svg' },
  { code: 'CL', name: 'Chile', flagUrl: 'https://flagcdn.com/cl.svg' },
  { code: 'CR', name: 'Costa Rica', flagUrl: 'https://flagcdn.com/cr.svg' },
  { code: 'CU', name: 'Cuba', flagUrl: 'https://flagcdn.com/cu.svg' },
  { code: 'EC', name: 'Ecuador', flagUrl: 'https://flagcdn.com/ec.svg' },
  { code: 'SV', name: 'El Salvador', flagUrl: 'https://flagcdn.com/sv.svg' },
  { code: 'GT', name: 'Guatemala', flagUrl: 'https://flagcdn.com/gt.svg' },
  { code: 'HN', name: 'Honduras', flagUrl: 'https://flagcdn.com/hn.svg' },
  { code: 'NI', name: 'Nicaragua', flagUrl: 'https://flagcdn.com/ni.svg' },
  { code: 'PA', name: 'Panamá', flagUrl: 'https://flagcdn.com/pa.svg' },
  { code: 'PY', name: 'Paraguay', flagUrl: 'https://flagcdn.com/py.svg' },
  { code: 'PE', name: 'Perú', flagUrl: 'https://flagcdn.com/pe.svg' },
  { code: 'PR', name: 'Puerto Rico', flagUrl: 'https://flagcdn.com/pr.svg' },
  { code: 'DO', name: 'República Dominicana', flagUrl: 'https://flagcdn.com/do.svg' },
  { code: 'UY', name: 'Uruguay', flagUrl: 'https://flagcdn.com/uy.svg' },
  { code: 'VE', name: 'Venezuela', flagUrl: 'https://flagcdn.com/ve.svg' }
];